/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as TvRouteImport } from './routes/tv'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as TvSectionRouteImport } from './routes/tv_.$section'
import { Route as AuthenticatedAccessIndexRouteImport } from './routes/_authenticated/access/index'
import { Route as AuthenticatedAdguardIndexRouteImport } from './routes/_authenticated/adguard/index'
import { Route as AuthenticatedAiIndexRouteImport } from './routes/_authenticated/ai/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedBackupsIndexRouteImport } from './routes/_authenticated/backups/index'
import { Route as AuthenticatedDisksIndexRouteImport } from './routes/_authenticated/disks/index'
import { Route as AuthenticatedDockerIndexRouteImport } from './routes/_authenticated/docker/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedInternetIndexRouteImport } from './routes/_authenticated/internet/index'
import { Route as AuthenticatedMediaIndexRouteImport } from './routes/_authenticated/media/index'
import { Route as AuthenticatedNetworkIndexRouteImport } from './routes/_authenticated/network/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedSitesIndexRouteImport } from './routes/_authenticated/sites/index'
import { Route as AuthenticatedSystemIndexRouteImport } from './routes/_authenticated/system/index'
import { Route as AuthenticatedTelegramIndexRouteImport } from './routes/_authenticated/telegram/index'
import { Route as AuthenticatedTorrentsIndexRouteImport } from './routes/_authenticated/torrents/index'
import { Route as AuthenticatedWirelessIndexRouteImport } from './routes/_authenticated/wireless/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const TvSectionRoute = TvSectionRouteImport.update({
  id: '/tv_/$section',
  path: '/tv/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccessIndexRoute =
  AuthenticatedAccessIndexRouteImport.update({
    id: '/access/',
    path: '/access/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdguardIndexRoute =
  AuthenticatedAdguardIndexRouteImport.update({
    id: '/adguard/',
    path: '/adguard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiIndexRoute = AuthenticatedAiIndexRouteImport.update({
  id: '/ai/',
  path: '/ai/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBackupsIndexRoute =
  AuthenticatedBackupsIndexRouteImport.update({
    id: '/backups/',
    path: '/backups/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDisksIndexRoute = AuthenticatedDisksIndexRouteImport.update({
  id: '/disks/',
  path: '/disks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDockerIndexRoute =
  AuthenticatedDockerIndexRouteImport.update({
    id: '/docker/',
    path: '/docker/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternetIndexRoute =
  AuthenticatedInternetIndexRouteImport.update({
    id: '/internet/',
    path: '/internet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaIndexRoute = AuthenticatedMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkIndexRoute =
  AuthenticatedNetworkIndexRouteImport.update({
    id: '/network/',
    path: '/network/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSitesIndexRoute = AuthenticatedSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemIndexRoute =
  AuthenticatedSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTelegramIndexRoute =
  AuthenticatedTelegramIndexRouteImport.update({
    id: '/telegram/',
    path: '/telegram/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTorrentsIndexRoute =
  AuthenticatedTorrentsIndexRouteImport.update({
    id: '/torrents/',
    path: '/torrents/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWirelessIndexRoute =
  AuthenticatedWirelessIndexRouteImport.update({
    id: '/wireless/',
    path: '/wireless/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/tv': typeof TvRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/tv/$section': typeof TvSectionRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/access/': typeof AuthenticatedAccessIndexRoute
  '/adguard/': typeof AuthenticatedAdguardIndexRoute
  '/ai/': typeof AuthenticatedAiIndexRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/backups/': typeof AuthenticatedBackupsIndexRoute
  '/disks/': typeof AuthenticatedDisksIndexRoute
  '/docker/': typeof AuthenticatedDockerIndexRoute
  '/internet/': typeof AuthenticatedInternetIndexRoute
  '/media/': typeof AuthenticatedMediaIndexRoute
  '/network/': typeof AuthenticatedNetworkIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/sites/': typeof AuthenticatedSitesIndexRoute
  '/system/': typeof AuthenticatedSystemIndexRoute
  '/telegram/': typeof AuthenticatedTelegramIndexRoute
  '/torrents/': typeof AuthenticatedTorrentsIndexRoute
  '/wireless/': typeof AuthenticatedWirelessIndexRoute
}
export interface FileRoutesByTo {
  '/tv': typeof TvRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/tv/$section': typeof TvSectionRoute
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/access': typeof AuthenticatedAccessIndexRoute
  '/adguard': typeof AuthenticatedAdguardIndexRoute
  '/ai': typeof AuthenticatedAiIndexRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/backups': typeof AuthenticatedBackupsIndexRoute
  '/disks': typeof AuthenticatedDisksIndexRoute
  '/docker': typeof AuthenticatedDockerIndexRoute
  '/internet': typeof AuthenticatedInternetIndexRoute
  '/media': typeof AuthenticatedMediaIndexRoute
  '/network': typeof AuthenticatedNetworkIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/sites': typeof AuthenticatedSitesIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/telegram': typeof AuthenticatedTelegramIndexRoute
  '/torrents': typeof AuthenticatedTorrentsIndexRoute
  '/wireless': typeof AuthenticatedWirelessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/tv': typeof TvRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/tv_/$section': typeof TvSectionRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/access/': typeof AuthenticatedAccessIndexRoute
  '/_authenticated/adguard/': typeof AuthenticatedAdguardIndexRoute
  '/_authenticated/ai/': typeof AuthenticatedAiIndexRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/backups/': typeof AuthenticatedBackupsIndexRoute
  '/_authenticated/disks/': typeof AuthenticatedDisksIndexRoute
  '/_authenticated/docker/': typeof AuthenticatedDockerIndexRoute
  '/_authenticated/internet/': typeof AuthenticatedInternetIndexRoute
  '/_authenticated/media/': typeof AuthenticatedMediaIndexRoute
  '/_authenticated/network/': typeof AuthenticatedNetworkIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/sites/': typeof AuthenticatedSitesIndexRoute
  '/_authenticated/system/': typeof AuthenticatedSystemIndexRoute
  '/_authenticated/telegram/': typeof AuthenticatedTelegramIndexRoute
  '/_authenticated/torrents/': typeof AuthenticatedTorrentsIndexRoute
  '/_authenticated/wireless/': typeof AuthenticatedWirelessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tv'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/tv/$section'
    | '/errors/$error'
    | '/access/'
    | '/adguard/'
    | '/ai/'
    | '/audit/'
    | '/backups/'
    | '/disks/'
    | '/docker/'
    | '/internet/'
    | '/media/'
    | '/network/'
    | '/notifications/'
    | '/sites/'
    | '/system/'
    | '/telegram/'
    | '/torrents/'
    | '/wireless/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/tv'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/tv/$section'
    | '/'
    | '/errors/$error'
    | '/access'
    | '/adguard'
    | '/ai'
    | '/audit'
    | '/backups'
    | '/disks'
    | '/docker'
    | '/internet'
    | '/media'
    | '/network'
    | '/notifications'
    | '/sites'
    | '/system'
    | '/telegram'
    | '/torrents'
    | '/wireless'
  id:
    | '__root__'
    | '/_authenticated'
    | '/tv'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/tv_/$section'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/access/'
    | '/_authenticated/adguard/'
    | '/_authenticated/ai/'
    | '/_authenticated/audit/'
    | '/_authenticated/backups/'
    | '/_authenticated/disks/'
    | '/_authenticated/docker/'
    | '/_authenticated/internet/'
    | '/_authenticated/media/'
    | '/_authenticated/network/'
    | '/_authenticated/notifications/'
    | '/_authenticated/sites/'
    | '/_authenticated/system/'
    | '/_authenticated/telegram/'
    | '/_authenticated/torrents/'
    | '/_authenticated/wireless/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  TvRoute: typeof TvRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  TvSectionRoute: typeof TvSectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/tv_/$section': {
      id: '/tv_/$section'
      path: '/tv/$section'
      fullPath: '/tv/$section'
      preLoaderRoute: typeof TvSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/access/': {
      id: '/_authenticated/access/'
      path: '/access'
      fullPath: '/access/'
      preLoaderRoute: typeof AuthenticatedAccessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adguard/': {
      id: '/_authenticated/adguard/'
      path: '/adguard'
      fullPath: '/adguard/'
      preLoaderRoute: typeof AuthenticatedAdguardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/': {
      id: '/_authenticated/ai/'
      path: '/ai'
      fullPath: '/ai/'
      preLoaderRoute: typeof AuthenticatedAiIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backups/': {
      id: '/_authenticated/backups/'
      path: '/backups'
      fullPath: '/backups/'
      preLoaderRoute: typeof AuthenticatedBackupsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disks/': {
      id: '/_authenticated/disks/'
      path: '/disks'
      fullPath: '/disks/'
      preLoaderRoute: typeof AuthenticatedDisksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docker/': {
      id: '/_authenticated/docker/'
      path: '/docker'
      fullPath: '/docker/'
      preLoaderRoute: typeof AuthenticatedDockerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/internet/': {
      id: '/_authenticated/internet/'
      path: '/internet'
      fullPath: '/internet/'
      preLoaderRoute: typeof AuthenticatedInternetIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media/': {
      id: '/_authenticated/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof AuthenticatedMediaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network/': {
      id: '/_authenticated/network/'
      path: '/network'
      fullPath: '/network/'
      preLoaderRoute: typeof AuthenticatedNetworkIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sites/': {
      id: '/_authenticated/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthenticatedSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/': {
      id: '/_authenticated/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof AuthenticatedSystemIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/telegram/': {
      id: '/_authenticated/telegram/'
      path: '/telegram'
      fullPath: '/telegram/'
      preLoaderRoute: typeof AuthenticatedTelegramIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/torrents/': {
      id: '/_authenticated/torrents/'
      path: '/torrents'
      fullPath: '/torrents/'
      preLoaderRoute: typeof AuthenticatedTorrentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wireless/': {
      id: '/_authenticated/wireless/'
      path: '/wireless'
      fullPath: '/wireless/'
      preLoaderRoute: typeof AuthenticatedWirelessIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAccessIndexRoute: typeof AuthenticatedAccessIndexRoute
  AuthenticatedAdguardIndexRoute: typeof AuthenticatedAdguardIndexRoute
  AuthenticatedAiIndexRoute: typeof AuthenticatedAiIndexRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedBackupsIndexRoute: typeof AuthenticatedBackupsIndexRoute
  AuthenticatedDisksIndexRoute: typeof AuthenticatedDisksIndexRoute
  AuthenticatedDockerIndexRoute: typeof AuthenticatedDockerIndexRoute
  AuthenticatedInternetIndexRoute: typeof AuthenticatedInternetIndexRoute
  AuthenticatedMediaIndexRoute: typeof AuthenticatedMediaIndexRoute
  AuthenticatedNetworkIndexRoute: typeof AuthenticatedNetworkIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedSitesIndexRoute: typeof AuthenticatedSitesIndexRoute
  AuthenticatedSystemIndexRoute: typeof AuthenticatedSystemIndexRoute
  AuthenticatedTelegramIndexRoute: typeof AuthenticatedTelegramIndexRoute
  AuthenticatedTorrentsIndexRoute: typeof AuthenticatedTorrentsIndexRoute
  AuthenticatedWirelessIndexRoute: typeof AuthenticatedWirelessIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAccessIndexRoute: AuthenticatedAccessIndexRoute,
  AuthenticatedAdguardIndexRoute: AuthenticatedAdguardIndexRoute,
  AuthenticatedAiIndexRoute: AuthenticatedAiIndexRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedBackupsIndexRoute: AuthenticatedBackupsIndexRoute,
  AuthenticatedDisksIndexRoute: AuthenticatedDisksIndexRoute,
  AuthenticatedDockerIndexRoute: AuthenticatedDockerIndexRoute,
  AuthenticatedInternetIndexRoute: AuthenticatedInternetIndexRoute,
  AuthenticatedMediaIndexRoute: AuthenticatedMediaIndexRoute,
  AuthenticatedNetworkIndexRoute: AuthenticatedNetworkIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedSitesIndexRoute: AuthenticatedSitesIndexRoute,
  AuthenticatedSystemIndexRoute: AuthenticatedSystemIndexRoute,
  AuthenticatedTelegramIndexRoute: AuthenticatedTelegramIndexRoute,
  AuthenticatedTorrentsIndexRoute: AuthenticatedTorrentsIndexRoute,
  AuthenticatedWirelessIndexRoute: AuthenticatedWirelessIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  TvRoute: TvRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  TvSectionRoute: TvSectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
